### ISSUE TITLE
Newest update no longer registers keyboard presses, horizontal resizing

### ISSUE THREAD

**Issue by ijustlovemath** [thedmd/pianobar-windows#10]
version is 2015.08.25. Previous version was 2013.05.* (can't remember the date). System specs: Windows 8.1 on Lenovo T530, i7 3520M, 8GB Lenovo RAM.

**Comment by ijustlovemath** [comment]
I've managed to get it to register all but the pause key.

**Comment by thedmd** [comment]
@ijustlovemath try latest release, there was a bug introduced by new player backend which is now fixed.
