### ISSUE TITLE
Using PandoraGlobal proxy with Pianobar

### ISSUE THREAD

**Issue by eoin71** [thedmd/pianobar-windows#12]
Hello, i can't seem to get pianobar working with pandoraglobal proxy. 

This line in the config file is the problem i believe.

control_proxy = http://proxy_user:proxy_pass@proxy_address:proxy_port

The error reported is pandora is not available in your country. So proxy is obviously not working. 

proxy_user and proxy_pass i have. However i cannot find which address to use and port. 
I have the other lines uncommented as required to use PandoraGlobal in the config file.

Thanks for any help !

**Comment by thedmd** [comment]
Try:
control_proxy = http://<proxy_user>:<proxy_pass>@proxy.globalpandora.com:443

**Comment by thedmd** [comment]
Closing in advance. I tried GlobalPandora and it works.
