### ISSUE TITLE
TLS Fingerprint

### ISSUE THREAD

**Issue by Hexalt** [thedmd/pianobar-windows#14]
10/19/2015 was when the new cert was created for their website. I don't know if that is the same site that pianobar uses.

**Comment by foobar0815** [comment]
`tls_fingerprint = 13CC51AC0C31CD96C55015C76914360F7AC41A00`

works at least for version 2013.05.19-win32 (I'm still using the older binaries because I'm affected by bug #13)

**Comment by Tobithy** [comment]
Thanks foobar, I added that to my pianobar.cfg and now it's working fine. For future reference, it looks like it's the SHA1 fingerprint obtained from https://tuner.pandora.com. I wonder if they will get rid of the SHA1 fingerprint next year when they are phased out in favor of SHA256.

**Comment by marcb1387** [comment]
I also had the same issues and the tls_fingerprint resolved it. Thanks.

**Comment by ablackbu** [comment]
Thanks for the updated fingerprint foobar0815.

**Comment by a236jose2** [comment]
And the issue is back again. Changeing my thumbprint to match ‎fc 2e 6a f4 9f c6 3a ed ad 10 78 dc 22 d1 18 5b 80 9e 75 34 does't work.

**Comment by nighthawk663** [comment]
I was just looking in to this myself. I found the new fingerprint:
tls_fingerprint = FC2E6AF49FC63AEDAD1078DC22D1185B809E7534

**Comment by thedmd** [comment]
`tls_fingerprint` is no longer a thing. Mainline dropped it in favor of cURL. This port did follow by relying on WinHTTP to handle certificate verification.

Old releases (2013) however still need it, because validation was not implemented in terms of CA.
