### ISSUE TITLE
How do I install this on windows?

### ISSUE THREAD

**Issue by hsingh23** [thedmd/pianobar-windows#15]

**Comment by thedmd** [comment]
You can checkout binaries which live on separate repository:
https://github.com/thedmd/pianobar-windows-binaries

**Comment by darthwalsh** [comment]
@thedmd Thanks for compiling the binaries! I was getting ready to start installing all sorts of libraries...

If it's not too much to ask, it might be worthwhile to set up a [Chocolately](https://chocolatey.org/) package and then the Windows install is even easier :)

**Comment by darthwalsh** [comment]
With the updated README, I think you can close this?
