### ISSUE TITLE
Global hotkeys/media keys?

### ISSUE THREAD

**Issue by ufuksarp** [thedmd/pianobar-windows#20]
Is it possible? It's sort of annoying having to open the Pianobar window to pause, skip, like, dislike the song while gaming etc...

**Comment by thedmd** [comment]
Hello @ufuksarp,
I think it is. I need to make some research about it.

**Comment by dan-drews** [comment]
Any update on this?

**Comment by thedmd** [comment]
@dan-drews Please checkout new release which add support for hot keys.

https://github.com/thedmd/pianobar-windows/releases

If you find any bug, please open new issue. Thanks!
