### ISSUE TITLE
Can I use my media keys after the new global hotkey addition?

### ISSUE THREAD

**Issue by ufuksarp** [thedmd/pianobar-windows#25]
I asked and you delievered, I really appreciate it. It was a feature much needed. But how do I set media keys as hotkeys?

**Comment by eldorel** [comment]
I can get regular keys like shift + alt + p to work, but media keys and function keys do not appear to work at all (or the supported key names are something nonstandard). 

I would like to be able to map play/pause/skip to the media keys, and 'ban this song' to Ctrl+Shift+F4... 

I was using a custom AHK script to do this, but having it working natively would be amazing.

**Comment by thedmd** [comment]
@ufuksarp, @eldorel Media keys now works. Please checkout [2020.04.20](https://github.com/thedmd/pianobar-windows/releases/tag/2020.04.20) release.

**Comment by eldorel** [comment]
A little late on my part, but thank you very much. 
This works perfectly.
