### ISSUE TITLE
Pandora's new Modes feature

### ISSUE THREAD

**Issue by ufuksarp** [thedmd/pianobar-windows#26]
Is this going to be added in feature releases?

**Comment by thedmd** [comment]
I maintain project and make sure port is up to date, but I do not develop new features, sorry.
If new functionality is added to original project https://github.com/PromyLOPh/pianobar I usually cherry pick it here.
PR's are also welcome.

**Comment by thedmd** [comment]
Playlist modes are available in latest release:
[2022.04.16](https://github.com/thedmd/pianobar-windows/releases/tag/2022.04.16)

**Comment by ufuksarp** [comment]
How can we use it?

**Comment by thedmd** [comment]
Quoting https://github.com/PromyLOPh/pianobar/issues/711#issuecomment-770912794:
> You can change the mode by pressing = and then m (default keys), (...)
