### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Malarne** [thedmd/pianobar-windows#29]
### Subject of the issue
I was trying to run pianobar on my win10 computer, after setting up some free proxy to have it not throw "pandora not available in your country" i faced a new error: Segmentation fault (https://imgur.com/a/xT1fFJI)

### Your environment
* version of pianobar: 2019.05.03
* Windows 10
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself) -> no idea
* your config file
control_proxy = http://my.proxy.url:port/
user = my@email
password = MyAmazingP4SsW0rD

### Steps to reproduce
Try setting up a control_proxy with some free http proxy found on the web ?

### Expected behaviour
pianobar run fine and play music

### Actual behaviour
Segmentation fault

**Comment by thedmd** [comment]
I found that there is indeed a crash for some short proxy assesses/ports.

**Comment by thedmd** [comment]
I also need to edit issue template :)

**Comment by thedmd** [comment]
Please reopen if crash still exists on latest release.
