### ISSUE TITLE
Trying to set media keys to hotkeys

### ISSUE THREAD

**Issue by legolasdimir** [thedmd/pianobar-windows#30]
### Subject of the issue
When i try to add a keyboard shortcut to use my media keys from my keyboard in pianobar

### Your environment
* pianobar-2019.05.03-x64
* Windows 10 ent 1903
The config file is attached
[pianobar.txt](https://github.com/thedmd/pianobar-windows/files/4168189/pianobar.txt)

### Steps to reproduce
set one of the play or pause keybindings to Media_Play_Pause or whatever the key input is from the keyboard.  ( i get this information from AutoHotkey)
### Expected behavior
The song should play or pause. (this may be just a matter of getting the correct info to put in the config file)

### Actual behavior
Nothing

##extra notes
It looks like other people have reported this in issue #20

**Comment by thedmd** [comment]
Media keys now works as expected. Please try latest release [2020.04.20](https://github.com/thedmd/pianobar-windows/releases/tag/2020.04.20).

Details about available media keys and actions are in release note.
