### ISSUE TITLE
Still having media key issues

### ISSUE THREAD

**Issue by legolasdimir** [thedmd/pianobar-windows#31]
### Subject of the issue
Media keys are not working after the latest release

# Your environment
*version 2020.04.20
*windows 10 1909
[pianobar github.txt](https://github.com/thedmd/pianobar-windows/files/4511284/pianobar.github.txt)

### Steps to reproduce
Try to use global media keys in pianobar

### Expected behavior
The song should play or pause as expected

### Actual behavior
Nothing happens

Please look at my configuration file and tell me if I have made some kind of mistake. Previously the hotkey string was in all caps but that did not work either.

**Comment by thedmd** [comment]
Hello,

To achieve play/pause functionality please bind hotkey only to `hk_act_songpausetoggle`.

Also on Windows one hotkey can be used only once. Looking at your config play/pause button was bound to play action only.

In other words there are three lines that need to be changed:
```
hk_act_songpausetoggle = media_play_pause
#hk_act_songplay = media_play_pause
#hk_act_songpause = media_play_pause
```

**Comment by legolasdimir** [comment]
It seems that the logitech software called setpoint that lets you customize certain keys was intercepting the keystrokes. i tried to use keyboardstateview to view them and they didn't show until after I had disabled that software
