### ISSUE TITLE
search broken?

### ISSUE THREAD

**Issue by github-account1111** [thedmd/pianobar-windows#32]
### Subject of the issue
I am unable to find the songs and artists I was easily able to find via the webapp.

### Your environment
* version of pianobar 2020.04.20
* your system version Windows LTSC
* your config file (without login or password please)

### Steps to reproduce
Log in, press `c`, enter artist and song name (e.g. "king plague ave plague"), press enter.

### Expected behaviour
Song is found.

### Actual behaviour
Something unrelated comes up. In the example above I get "Ben E. King."

**Comment by github-account1111** [comment]
Turns out I can't start a station with those artists / tracks (why are they there on Pandora then?), which is why it didn't find anything.

**Comment by thedmd** [comment]
Search seems to work, Pandora suggest this:
![image](https://user-images.githubusercontent.com/1197433/88842926-91f73c00-d1e0-11ea-8560-46638078f4d1.png)

Not sure and this is the correct result. If you try Pandora.com you get something else?

**Comment by github-account1111** [comment]
@thedmd it's the correct result. The problem isn't on Pianobar's side. [This](https://www.pandora.com/artist/king-plague/ave-plague-single/ave-plague/TRK4953rZwJ5z5q) is available on Pandora's webapp, but it cannot be listened to in a radio (which makes me wonder where it can be listened to, since Pandora is just an online radio, unless I'm missing something).

**Comment by thedmd** [comment]
I wonder if this is due to platform restrictions. By default pianobar pose as an Android app. If you have a subscription you can uncomment:
```
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
```
Pianobar will then act like a web player.
