### ISSUE TITLE
Pianobar on android - noroot

### ISSUE THREAD

**Issue by oakes8585** [thedmd/pianobar-windows#34]
been trying to get pianobar to run on android with no luck :( is there a work aroimd for this? Ve nice to use this application while beimg mobile without having to use my laptop.

Android version  9
Mediatek cell phone and tab 910

**Comment by thedmd** [comment]
Hi @oakes8585 

You may have better luck with original [pianobar](https://github.com/PromyLOPh/pianobar) project. Mine is just port to Windows, original works on Linux which give you fighting chance of running it on Android.

Please reopen if you find, my assessment wasn't correct.
