### ISSUE TITLE
Pianobar will not log in. Get invalid auth token message

### ISSUE THREAD

**Issue by legolasdimir** [thedmd/pianobar-windows#37]
### Subject of the issue
After some recent maintenance on Pandora, my pianobar installation has quit working entirely. It will pull up and get as far as the login text where it will sit for a seemingly random period of time upon which an error will appear for less than a second and the app will close. I have tried this on more than one windows machine with the exact same release and configuration file with the same results.

### Your environment
* 2020.04.20
* Windows 10 Enterprise 21h2
* your config file 

(place holder values inserted for username and password to illustrate formatting)

# Uncomment the control_proxy line if you would like to set up a proxy connection for pianobar
#control_proxy = http://<proxy_user>:<proxy_pass>@<proxy_address>:<proxy_port>

user = X
password = X

#width = 220
#height = 60

# Keybindings
#hk_act_help = ?
#hk_act_songlove = +
#hk_act_songban = -
#hk_act_stationaddmusic = a
#hk_act_stationcreate = c
#hk_act_stationdelete = d
#hk_act_songexplain = e
#hk_act_stationaddbygenre = g
#hk_act_history = i
#hk_act_addshared = j
hk_act_songnext = media_next_track
hk_act_songpausetoggle = media_play_pause 
#hk_act_quit = q
#hk_act_stationrename = r
#hk_act_stationchange = s
#hk_act_songtired = t
#hk_act_upcoming = u
#hk_act_stationselectquickmix = x
#hk_act_bookmark = ctrl + b
#hk_act_voldown = (
#hk_act_volup = )
#hk_managestation = ctrl + m
#hk_act_stationcreatefromsong = v
#hk_act_songplay = media_play_pause
#hk_act_songpause = media_play_pause
#hk_act_volreset = ^
#hk_act_settings = !

#-------------------------------------------------------------------------------
# Uncomment these if you're using GlobalPandora.com

#rpc_host = internal-tuner.pandora.com
#partner_user = pandora one
#partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
#device = D01
#encrypt_password = 2%3WCL*JU$MP]4
#decrypt_password = U#IO$RZPAB%VX2
#tls_fingerprint = B0A1EB460B1B6F33A1B6CB500C6523CB2E6EC946

# Messages with colors using terminal escape codes
format_nowplaying_song = "[92m%t[0m" by "[96m%a[0m" on "[93m%l[0m"[91m%r[0m%@%s
format_nowplaying_station = Station "[95m%n[0m" [90m(%i)[0m
format_list_song = %i) %a - [92m%t[0m%r
format_msg_info = [97m(i) [0m%s
format_msg_nowplaying = [36m|>[0m  %s
format_msg_time = [90m#   [97m%s[0m
format_msg_err = [90m/!\[0m %s
format_msg_question = [97m[?][0m %s
format_msg_debug = [90m%s[0m

### Steps to reproduce
Simply open the app and let it try to log in.

### Expected behavior
The app should log in and present my stations.

### Actual behavior
It hangs on the login message for a random period of time then presents the error : Error: Invalid Auth Token very very quickly. I had to do a screen capture and slow it down to less than half speed to get a screenshot.
![image (1)](https://user-images.githubusercontent.com/21345773/137019799-a5a330f1-3fde-46a1-a35b-a7c414b051d6.png)

**Comment by thedmd** [comment]
Can you please checkout if latest release resolve your problem?
[2022.04.16](https://github.com/thedmd/pianobar-windows/releases/tag/2022.04.16)

**Comment by legolasdimir** [comment]
The issue resolved itself some time ago then came back randomly then went away then came back for a little bit. After doing some checking it seems to actually be network related to my local network. If I tethered my phone and ran my computer on hotspot I was able to log in just fine. I will update when I get a chance.

**Comment by thedmd** [comment]
OK. I will consider issue resolved on pianobar side for now.
