### ISSUE TITLE
Windows terminal window scroll

### ISSUE THREAD

**Issue by mrainess** [thedmd/pianobar-windows#5]
Running pianobar on LInux, scrolling the terminal window works normally. If I do "s" to show the stations list, I can use the mouse scroll wheel or shift pgup/pgdn to see the entire llist. Running on Windows 7, in a cmd shell console window, if I do "s" I cannot scroll back. The scroll bar does not appear and the mouse wheel does not scroll the console window. Is there a work around? Possibly the method pianobar is using to write to the console window is the problem. If I use the dir command, and the output exceeds the height of the window, scroll bars appear and the mouse wheel will scroll the window. This does not happen when using "s" and the number of lines of text exceed the console window height.

**Comment by Kifferzwerg** [comment]
So did anyone figure this out? Still is an issue on current version running on windows 8.

**Comment by mjsmith707** [comment]
Definitely want to second this. Makes it somewhat unusable if you've got too many stations or search for an artist/track that returns lots of results.

**Comment by ijustlovemath** [comment]
Thirding this. Glad it's not only me.

**Comment by thedmd** [comment]
Scrollbar is back.

**Comment by Kifferzwerg** [comment]
So is the scroll bar back in a new version? If so wo is the links? Also, I found you can search for artist based on characters in their names with the "s" command. So to find Why? you can seach w. h. y or even ?. So here's some actual help.
