### ISSUE TITLE
Windows Error 

### ISSUE THREAD

**Issue by boredftw** [thedmd/pianobar-windows#6]
I'm getting this error when trying to listen to music I have tried downloading the code that was listed when I Googled this issue and still to no avail it skips the song that is currently playing. Is there like a permanent fix to this? Or a file I can add like I said I tried the one where this issue was listed a year ago however this issue still happens. 

I haven't been able to reproduce the problem until actually I opened up any type of internet browser that's when it starts causing errors like Decoding Error : Channel coupling not yet implemented, Bitstream value not allowed by specification etc. I'm not sure if that was the cause of it or not but it was working just fine when I didn't have one open if that makes any sense. Another error came up where PCE shall have the first element in a frame.

I'm running Windows 7 home premium I believe not sure which version I have I think it's the most recent though from 9/16 or a date like that however I will check when I get home from work this afternoon.

**Comment by thedmd** [comment]
Do you have this problem with every track or only with some of them?

**Comment by thedmd** [comment]
@boredftw Can you check out latest build for this issue?

**Comment by thedmd** [comment]
Fixed in 2015.12.10 release.
