### ISSUE TITLE
Does not receive key press input when run from a Cygwin-based shell

### ISSUE THREAD

**Issue by maurizi** [thedmd/pianobar-windows#8]
When I run `pianobar.exe` from `cmd.exe` or Git Bash everything works fine.

When I run it from `mintty` and `bash`, it can't receive any key press inputs (I press `?` and nothing happens).

**Comment by mjsmith707** [comment]
Another issue in cygwin for me was never getting to the password prompt. Either enter wasn't being consumed or something else broke.

**Comment by thedmd** [comment]
mintty is avoiding Windows Console API by wrapping it in some hidden console (as far as I know). I have no clue how I can fix that.

**Comment by thedmd** [comment]
Closing for now. Subject may return if a reasonable way of implementing this materialize.
