### ISSUE TITLE
"Select Station" shutdown bug

### ISSUE THREAD

**Issue by ijustlovemath** [thedmd/pianobar-windows#9]
After pausing for some time, resuming the song finishes that song (so not too long, as it would have just received a new playlist), and the you get something like "Forbidden" "select station". Typing in a vlid or invalid station causes pianobar to stop responding, requiring a shutdown.

**Comment by thedmd** [comment]
@ijustlovemath Can you  try to reproduce issue with latest build?

**Comment by ijustlovemath** [comment]
Not anymore. It was rare to begin with, but I'll keep my eye out for it.
